spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
  jackson:
    visibility:
      field: any
  profiles:
    active: dev
  cache:
    jcache:
      config: classpath:ehcache.xml
server:
  servlet:
    context-path: "/api"
management:
  endpoints:
    web:
      exposure:
        include: "*"