spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
  jackson:
    visibility:
      field: any
  profiles:
    active: dev
server:
  servlet:
    context-path: "/api"