spring:
  liquibase:
    change-log: classpath:db/changelog/master-dev.xml
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:test