spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: off
  datasource:
    url: jdbc:mysql://localhost:3306/beer_api
    username: root
    password: 1234